### ISSUE TITLE
Design a business card with HTML just like social images 

### ISSUE THREAD

**Issue by krushiraj** [krushiraj/krushiraj.github.io#28]

**Comment by aanchalsharmaa1024** [comment]
pls assign this to me

**Comment by krushiraj** [comment]
Sorry @aanchalsharmaa1024 . Before I could see your comment, I have started on it. If you would like to work on some other first issue please let me know. I have a couple of things to work on.

**Comment by aanchalsharmaa1024** [comment]
Yes.. If u have some issues regarding html, tailwind css.. Pls assign me..

**Comment by krushiraj** [comment]
https://github.com/krushiraj/notion-db-form

Can you have a look at this and see if you can work on it. I have a couple of fixes or features to be implemented. If you you can work on them I will create the issues.
